name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.1
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.13.3
  node_interop: ^2.0.1
  node_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.3
  build_node_compilers:
    git: # temporary until NNBD approved for main package
      url: https://github.com/SupposedlySam/node-interop.git
      path: build_node_compilers
  build_test: ^2.1.0
  pedantic: ^1.11.0
  test: ^1.17.4
